### PR TITLE
Check click/dblclick event target for direct videos

### LINKED ISSUE #9: Direct video click handler conflicts with other extensions
I just added an extension that adds some UI to standalone image and video tabs.
If I try to click on a button from this other extension, the event is intercepted by your extension, no matter where I click.
The other extension ([Imagus](https://chrome.google.com/webstore/detail/imagus/immpkjjlgappgfkkfieppnmlhakdmaab)) adds its HTML _outside_ the `<body>`, so your extension still considers it a "direct" video.

### PR DESCRIPTION
**Pull request by chris-oreilly**
Fixes #9 

I assumed that being able to click _outside_ the video to play/pause wasn't actually a feature.

### CODE REVIEW

**Comment by AjaxGb** [comment]
Used a similar but more readable solution (moved the reused code to a function).

**Comment by AjaxGb** [comment]
Also, clicks on the document background affecting the video was, indeed, intentional, and is maintained in this fix.

**Comment by chris-oreilly** [comment]
Works for me! Thanks for resolving this so quickly.

**Comment by AjaxGb** [comment]
No problem, the update should filter through the Chrome Web Store to you soon.

**Pull request closed without merging**
