### PR TITLE
First click selects video AND plays

### PR DESCRIPTION
**Pull request by chris-oreilly**
I didn't like having to click twice to start a video, especially since the first click doesn't _appear_ to do anything.

### CODE REVIEW

**Comment by chris-oreilly** [comment]
This also changes the result of double clicking an un-selected video. Before, the video would start playing; now it remains paused.

This seems like a good thing to me; toggling fullscreen shouldn't affect the play/pause state.

**Comment by AjaxGb** [comment]
I'd rather hold off on this one until I implement an options window, which is on my short-term to-do list. While I see your point, it also makes selecting a video without play/pausing it difficult at best (the control bar does not generate click events).

**Comment by chris-oreilly** [comment]
I understand. I was hesitant about suggesting such a major change. I'm content to use my own fork for now.

**Comment by AjaxGb** [comment]
Pushing this to the Chrome store now.

**Comment by AjaxGb** [comment]
It's not the default setting, but I think you'll be happy.

**Comment by chris-oreilly** [comment]
I am, thanks. I also like the click-to-play delay, which I was planning to add once the options page was set up.

**Pull request closed without merging**
